### PR TITLE
Adding German Strings

### PR DESCRIPTION
**Pull request by ThodeC**
This PR adds german string resources and designer.

Fixes - https://github.com/infinitespace-studios/VectorRumble/issues/5

### CODE REVIEW

**Comment by CartBlanche** [comment]
Hi @ThodeC Thanks the PR. We are just in the middle of some refactoring (see other PR) before we announce the update to this sample publicly. We'll take a look at this soon.

**Comment by ThodeC** [comment]
Hey @CartBlanche 

no hurry, but thanks a lot for the clarification, as this is my first real contribution to an open source project.

**Comment by CartBlanche** [comment]
@ThodeC I'm just creating the Credits screen. Would you like your fill name in there or just your Github handle?

**Comment by ThodeC** [comment]
Hey @CartBlanche You can add my full Name "Christian Thode" there, thanks a lot!

**Comment by CartBlanche** [comment]
@ThodeC it should be going in this PR - https://github.com/infinitespace-studios/VectorRumble/pull/35

**Pull request merged**
